#!/bin/bash

if [[ $# -ne 1 ]]
then
	echo "Usage: ./1-mysql_backup <passworda">
	exit 1
fi
mysqldump --all-databases --single-transaction --quick --lock-tables=false > backup.sql -u root --password="$1"
tar -zcvf $(date +%d-%m-%Y).tar.gz backup.sql
