#!/usr/bin/env bash

if [[ $# -ne 1 ]]
then
	echo "Usage: ./1-mysql_backup <password>"
	exit 1
fi
mysqldump --all-databases > "backup.sql" -u root --password="$1"
tar -zcvf "$(date +%d-%m-%Y).tar.gz" backup.sql
