#!/usr/bin/env bash
# This script will reconfigure the nginx server to listen at port 80 instead of 8080
pkill nginxp
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
