#!/usr/bin/env bash
#this script prints out fizzbuzz!

for ((i=1;i<=100;i++))
do
	let "f=i%3"
	let "b=i%5"
	if [ "$f" -eq 0 -a "$b" -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ "$f" -eq 0 ]
	then
		echo "Fizz"
	elif [ "$b" -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done

