#!/usr/bin/env bash
## This script will dispaly number from 1 to 20

START=1
x=$START

while [ $x -lt 21 ];
do
	echo "$x"
	case $x in
		4)
			echo "bad luck from China";;
		9)	
			echo "bad luck from Japan";;
		17)
			echo "bad luck from Italy"
	esac
	x=$((x+1))
done
