#!/usr/bin/env bash
## this Script checks a file
filename="holbertonschool"

if [ -e "$filename" ]
then
	echo "holbertonschool file exists"
	if [ -s "$filename" ]
	then
		echo "holbertonschool is not empty"
	else
		echo "holbertonschool is empty"
	fi
	if [ -f "$filename" ]
	then
		echo "holbertonschool is a regular file"
	fi
		
else
	echo "holbertonschool file does not exist"
fi
