#!/usr/bin/env bash
# This script will take 4 parameters and transfer a file

if [ -z "$3" ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	if [ -z "$4" ]
	then
		scp -o "StrictHostKeyChecking=no" "$1" "$3@$2":~/ 
	else
		scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/
	fi
fi
