#!/usr/bin/env bash
# This script will install nginx server on a remote machine
apt-get update
apt-get -y upgrade
apt-get -y install nginx
echo "Holberton School" > /usr/share/nginx/html/index.html
/etc/init.d/nginx restart
