#!/usr/bin/env bash
# This script will configure the redirection
NEWBLOCK="server_name localhost\;\n\tlocation \/redirect_me \{\n \t\treturn 301 https:\/\/www.youtube.com\/watch?v=dQw4w9WgXcQ;\n\t\}"
SEARCH="server_name localhost;"
sed -i --follow-symlinks "1,/$SEARCH/s/$SEARCH/$NEWBLOCK/" /etc/nginx/sites-enabled/default
service nginx restart
