#!/usr/bin/env bash
# This script fixes some issues and configures nginx to run on port 8080
sudo pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
